/*
 * Apps.java
 *
 * Created on Dec 30, 2010, 10:46:26 AM
 */
package vck;

import java.awt.Toolkit;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.channels.FileChannel;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.UIManager;

/**
 *
 * @author roman
 */
public class Apps extends javax.swing.JFrame {

    static ArrayList<String> sources = new ArrayList<String>();
    static ArrayList<DownloadFile> files = new ArrayList<DownloadFile>();
    static boolean useSystem, useData, useLib, wipeDalvik;
    static Apps instance;

    public Apps() {
        if (instance == null) {
            instance = this;
        }
        initComponents();
        Apps.getInstance().zipProgress.setVisible(false);
    }

    public static Apps getInstance() {
        if (instance == null) {
            instance = new Apps();
        }
        return instance;
    }

    private static void createDirectories() {
        new File("system/app").mkdirs();
        new File("data/app").mkdirs();
        new File("system/lib").mkdirs();
        new File("META-INF/com/google/android").mkdirs();

//        addApp("kitchen/META-INF/CERT.RSA", "META-INF/CERT.RSA");
//        addApp("kitchen/META-INF/CERT.SF", "META-INF/CERT.SF");
//        addApp("kitchen/META-INF/MANIFEST.MF", "META-INF/MANIFEST.MF");
    }

    private static void cleanUp() {
        deleteDir(new File("system"));
        deleteDir(new File("data"));
        deleteDir(new File("META-INF"));
    }

    public static void createUpdateScript() {
        //check whether to use data and system
        for (String entry : sources) {
            if (!useData && entry.startsWith("data")) {
                useData = true;
                System.out.println(entry + " setting data to true");
                //break;
            }
            if (!useSystem && entry.startsWith("system")) {
                useSystem = true;
                System.out.println(entry + " setting system to true");
                //break;
            }
        }



        //writing the script
        PrintWriter out = null;
        try {
            File f = new File("META-INF/com/google/android/update-script");
            FileWriter outFile = new FileWriter(f);
            out = new PrintWriter(outFile);
            int i = 1;

            if (wipeDalvik) {
                out.println("show_progress 0." + i + " 0");
                out.println("delete_recursive DATA:dalvik-cache");
                out.println("show_progress 0." + i + " 10");
                i++;
            }

            out.println("show_progress 0." + i + " 0");
            if (useSystem) {
                out.println("copy_dir PACKAGE:system SYSTEM:");
            }
            if (useData) {
                out.println("copy_dir PACKAGE:data DATA:");
            }
            out.println("show_progress 0." + i + " 10");
            out.close();

            //sources.add("META-INF/com/google/android/update-script");
        } catch (IOException ex) {
            Logger.getLogger(Apps.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static boolean deleteDir(File dir) {
        if (dir.isDirectory()) {
            String[] children = dir.list();
            for (int i = 0; i < children.length; i++) {
                boolean success = deleteDir(new File(dir, children[i]));
                if (!success) {
                    return false;
                }
            }
        }

        // The directory is now empty so delete it
        return dir.delete();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MmsGroup = new javax.swing.ButtonGroup();
        ModemGroup = new javax.swing.ButtonGroup();
        generateZipButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        utilitiesPanel = new javax.swing.JPanel();
        utilitiesTitaniumButton = new javax.swing.JCheckBox();
        utilitiesQuickBootButton = new javax.swing.JCheckBox();
        utilitiesRomManagerButton = new javax.swing.JCheckBox();
        utilitiesSpareParts = new javax.swing.JCheckBox();
        utilitiesSgsTools = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        launchersLauncherPro = new javax.swing.JCheckBox();
        launchersAdw = new javax.swing.JCheckBox();
        launchersGingerbread = new javax.swing.JCheckBox();
        launcherTouchWiz = new javax.swing.JCheckBox();
        launchersZeam = new javax.swing.JCheckBox();
        miscGingerbreadkb = new javax.swing.JCheckBox();
        miscDockHome = new javax.swing.JCheckBox();
        miscCarHome = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        mmsAospButton = new javax.swing.JRadioButton();
        touchWizMmsButton = new javax.swing.JRadioButton();
        mmsDontModifyButton = new javax.swing.JRadioButton();
        systemMms = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        vibrantAllShare = new javax.swing.JCheckBox();
        vibrantAvatar = new javax.swing.JCheckBox();
        vibrantMediahub = new javax.swing.JCheckBox();
        vibrantWriteandGo = new javax.swing.JCheckBox();
        vibrantGogo = new javax.swing.JCheckBox();
        vibrantLayar = new javax.swing.JCheckBox();
        vibrantMiniDiary = new javax.swing.JCheckBox();
        vibrantKindle = new javax.swing.JCheckBox();
        vibrantAmazon = new javax.swing.JCheckBox();
        vibrantMemo = new javax.swing.JCheckBox();
        vibrantWifiCalling = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        VibrantVisualVoicemail = new javax.swing.JCheckBox();
        vibrantThinkFree = new javax.swing.JCheckBox();
        vibrantTelenav = new javax.swing.JCheckBox();
        vibrantSlacker = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        vibrantTmoTV = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        wipeDalvikCacheToggle = new javax.swing.JCheckBox();
        zipName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        zipProgress = new javax.swing.JProgressBar();
        statusText = new javax.swing.JLabel();
        downloadFiles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vibrant Customization Kitchen");
        setIconImage(Toolkit.getDefaultToolkit().getImage("icon.png"));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        generateZipButton.setText("Generate ZIP");
        generateZipButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateZipButtonActionPerformed(evt);
            }
        });

        jTabbedPane1.setFocusable(false);

        utilitiesTitaniumButton.setText("Titanium Backup");
        utilitiesTitaniumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilitiesTitaniumButtonActionPerformed(evt);
            }
        });

        utilitiesQuickBootButton.setText("Quick Boot");
        utilitiesQuickBootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilitiesQuickBootButtonActionPerformed(evt);
            }
        });

        utilitiesRomManagerButton.setText("ROM Manager");
        utilitiesRomManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilitiesRomManagerButtonActionPerformed(evt);
            }
        });

        utilitiesSpareParts.setText("Spare Parts");
        utilitiesSpareParts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilitiesSparePartsActionPerformed(evt);
            }
        });

        utilitiesSgsTools.setText("SGS Tools");
        utilitiesSgsTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utilitiesSgsToolsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout utilitiesPanelLayout = new javax.swing.GroupLayout(utilitiesPanel);
        utilitiesPanel.setLayout(utilitiesPanelLayout);
        utilitiesPanelLayout.setHorizontalGroup(
            utilitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utilitiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(utilitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(utilitiesTitaniumButton)
                    .addComponent(utilitiesQuickBootButton)
                    .addComponent(utilitiesRomManagerButton)
                    .addComponent(utilitiesSgsTools)
                    .addComponent(utilitiesSpareParts))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        utilitiesPanelLayout.setVerticalGroup(
            utilitiesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utilitiesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(utilitiesTitaniumButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(utilitiesQuickBootButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(utilitiesRomManagerButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(utilitiesSpareParts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(utilitiesSgsTools)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Utilities", utilitiesPanel);

        launchersLauncherPro.setText("LauncherPro 8.2");
        launchersLauncherPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchersLauncherProActionPerformed(evt);
            }
        });

        launchersAdw.setText("ADW Launcher");
        launchersAdw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchersAdwActionPerformed(evt);
            }
        });

        launchersGingerbread.setText("Gingerbread Launcher");
        launchersGingerbread.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchersGingerbreadActionPerformed(evt);
            }
        });

        launcherTouchWiz.setText("TouchWiz Launcher");
        launcherTouchWiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launcherTouchWizActionPerformed(evt);
            }
        });

        launchersZeam.setText("Zeam");
        launchersZeam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchersZeamActionPerformed(evt);
            }
        });

        miscGingerbreadkb.setText("Gingerbread Keyboard");
        miscGingerbreadkb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miscGingerbreadkbActionPerformed(evt);
            }
        });

        miscDockHome.setText("Dock Home");
        miscDockHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miscDockHomeActionPerformed(evt);
            }
        });

        miscCarHome.setText("Car Home");
        miscCarHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miscCarHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(launchersLauncherPro)
                            .addComponent(launchersAdw)
                            .addComponent(launchersGingerbread))
                        .addGap(8, 8, 8)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(miscCarHome)
                            .addComponent(miscDockHome)
                            .addComponent(miscGingerbreadkb)))
                    .addComponent(launcherTouchWiz)
                    .addComponent(launchersZeam))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(miscCarHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(miscDockHome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(miscGingerbreadkb))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(launchersLauncherPro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(launchersAdw)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(launchersGingerbread)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(launcherTouchWiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(launchersZeam)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Launchers & Misc", jPanel4);

        MmsGroup.add(mmsAospButton);
        mmsAospButton.setText("AOSP Mms");
        mmsAospButton.setToolTipText("supports lock screen puzzle notifications");
        mmsAospButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmsAospButtonActionPerformed(evt);
            }
        });

        MmsGroup.add(touchWizMmsButton);
        touchWizMmsButton.setText("TouchWiz Mms");
        touchWizMmsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                touchWizMmsButtonActionPerformed(evt);
            }
        });

        MmsGroup.add(mmsDontModifyButton);
        mmsDontModifyButton.setSelected(true);
        mmsDontModifyButton.setText("Don't Modify");
        mmsDontModifyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmsDontModifyButtonActionPerformed(evt);
            }
        });

        systemMms.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Don't Modify", "AOSP Mms", "TouchWiz Mms" }));
        systemMms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemMmsActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Don't Modify", "AOSP Email", "TouchWiz Email" }));
        jComboBox2.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(mmsAospButton)
                        .addGap(51, 51, 51)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(touchWizMmsButton)
                    .addComponent(mmsDontModifyButton)
                    .addComponent(systemMms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mmsAospButton)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(touchWizMmsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mmsDontModifyButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(systemMms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        jTabbedPane1.addTab("System", jPanel2);

        ModemGroup.add(jRadioButton4);
        jRadioButton4.setText("JL5");
        jRadioButton4.setEnabled(false);

        ModemGroup.add(jRadioButton5);
        jRadioButton5.setText("JL4");
        jRadioButton5.setEnabled(false);

        ModemGroup.add(jRadioButton6);
        jRadioButton6.setText("JL2");
        jRadioButton6.setEnabled(false);

        ModemGroup.add(jRadioButton7);
        jRadioButton7.setText("JK6");
        jRadioButton7.setEnabled(false);

        ModemGroup.add(jRadioButton8);
        jRadioButton8.setText("JK2");
        jRadioButton8.setEnabled(false);

        ModemGroup.add(jRadioButton9);
        jRadioButton9.setSelected(true);
        jRadioButton9.setText("Don't Modify");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5)
                    .addComponent(jRadioButton6)
                    .addComponent(jRadioButton7)
                    .addComponent(jRadioButton8)
                    .addComponent(jRadioButton9))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jRadioButton9)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Modems", jPanel3);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 147, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Kernels", jPanel5);

        jPanel1.setEnabled(false);

        vibrantAllShare.setText("AllShare");
        vibrantAllShare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibrantAllShareActionPerformed(evt);
            }
        });

        vibrantAvatar.setText("Avatar");
        vibrantAvatar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibrantAvatarActionPerformed(evt);
            }
        });

        vibrantMediahub.setText("Mediahub");
        vibrantMediahub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibrantMediahubActionPerformed(evt);
            }
        });

        vibrantWriteandGo.setText("Write and Go");
        vibrantWriteandGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibrantWriteandGoActionPerformed(evt);
            }
        });

        vibrantGogo.setText("GoGo");
        vibrantGogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibrantGogoActionPerformed(evt);
            }
        });

        vibrantLayar.setText("Layar");
        vibrantLayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibrantLayarActionPerformed(evt);
            }
        });

        vibrantMiniDiary.setText("Mini Diary");
        vibrantMiniDiary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibrantMiniDiaryActionPerformed(evt);
            }
        });

        vibrantKindle.setText("Kindle");
        vibrantKindle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibrantKindleActionPerformed(evt);
            }
        });

        vibrantAmazon.setText("Amazon");
        vibrantAmazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibrantAmazonActionPerformed(evt);
            }
        });

        vibrantMemo.setText("Memo");
        vibrantMemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibrantMemoActionPerformed(evt);
            }
        });

        vibrantWifiCalling.setText("Wifi Calling");
        vibrantWifiCalling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibrantWifiCallingActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Audio Postcard");

        VibrantVisualVoicemail.setText("Visual Voicemail");
        VibrantVisualVoicemail.setEnabled(false);
        VibrantVisualVoicemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VibrantVisualVoicemailActionPerformed(evt);
            }
        });

        vibrantThinkFree.setText("Think Free");
        vibrantThinkFree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibrantThinkFreeActionPerformed(evt);
            }
        });

        vibrantTelenav.setText("Telenav");
        vibrantTelenav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibrantTelenavActionPerformed(evt);
            }
        });

        vibrantSlacker.setText("Slacker");
        vibrantSlacker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibrantSlackerActionPerformed(evt);
            }
        });

        jCheckBox5.setText("My Account");
        jCheckBox5.setEnabled(false);

        vibrantTmoTV.setText("T-Mobile TV");
        vibrantTmoTV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vibrantTmoTVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vibrantAvatar)
                    .addComponent(vibrantAllShare)
                    .addComponent(vibrantAmazon)
                    .addComponent(jCheckBox2)
                    .addComponent(vibrantGogo)
                    .addComponent(vibrantKindle))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vibrantMiniDiary)
                                    .addComponent(vibrantLayar)
                                    .addComponent(vibrantMediahub)
                                    .addComponent(vibrantMemo))
                                .addGap(10, 10, 10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jCheckBox5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vibrantTelenav)
                            .addComponent(vibrantTmoTV)
                            .addComponent(vibrantWriteandGo)
                            .addComponent(vibrantWifiCalling)
                            .addComponent(VibrantVisualVoicemail)
                            .addComponent(vibrantThinkFree)))
                    .addComponent(vibrantSlacker)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vibrantAllShare)
                    .addComponent(vibrantLayar)
                    .addComponent(vibrantTelenav))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vibrantThinkFree)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vibrantTmoTV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VibrantVisualVoicemail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vibrantWriteandGo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vibrantWifiCalling))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vibrantAmazon)
                            .addComponent(vibrantMediahub))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox2)
                            .addComponent(vibrantMemo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vibrantAvatar)
                            .addComponent(vibrantMiniDiary))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vibrantGogo)
                            .addComponent(jCheckBox5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vibrantKindle)
                            .addComponent(vibrantSlacker))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Vibrant Apps", jPanel1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("VCK v0.4");

        jLabel2.setText("by Roman");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel3.setForeground(new java.awt.Color(204, 0, 0));
        jLabel3.setText("ALPHA");
        jLabel3.setOpaque(true);

        wipeDalvikCacheToggle.setText("Wipe Dalvik Cache");
        wipeDalvikCacheToggle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wipeDalvikCacheToggleActionPerformed(evt);
            }
        });

        zipName.setText("flash");

        jLabel4.setText(".zip");

        zipProgress.setFocusable(false);

        statusText.setText("Status");

        downloadFiles.setText("Download Files");
        downloadFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadFilesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel2))))
                            .addComponent(zipProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(generateZipButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(downloadFiles, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(zipName, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4))
                            .addComponent(wipeDalvikCacheToggle)
                            .addComponent(statusText))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zipProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statusText)
                        .addGap(7, 7, 7)
                        .addComponent(wipeDalvikCacheToggle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(zipName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(downloadFiles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(generateZipButton)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static List<String> recursiveFileSearch(File dir) {
        //File systemFolder = new File("");
        List<String> list = new ArrayList<String>();
        if (dir.isDirectory()) {
            for (File f : dir.listFiles()) {
                if (!f.isDirectory()) {
                    System.out.println(f.getPath());
                    list.add(f.getPath());
                } else {
                    list.addAll(recursiveFileSearch(f));
                }
            }
        }
        return list;
    }

    private void generateZipButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generateZipButtonActionPerformed
        zipProgress.setVisible(true);
        System.out.println("sources size before zip creation: " + sources.size());
        Zip z = new Zip(files, this.zipName.getText());
        z.addPropertyChangeListener(
                new PropertyChangeListener() {

                    public void propertyChange(PropertyChangeEvent evt) {
                        if ("progress".equals(evt.getPropertyName())) {
                            zipProgress.setValue((Integer) evt.getNewValue());
                        }
                    }
                });

        z.execute();


        //        //folders should be created when program starts, cleaned when it closes
//        //file all files in /system/, /data/, and /META-INF/, add to sources
//        sources.clear();
//        sources.addAll(recursiveFileSearch(new File("META-INF")));
//        sources.addAll(recursiveFileSearch(new File("system")));
//        sources.addAll(recursiveFileSearch(new File("data")));
//        createUpdateScript();//generate update script based on files in sources
//
//        // Create a buffer for reading the files
//        byte[] buf = new byte[1024];
//
//        try {
//            // Create the ZIP file
//            String target = this.zipName.getText();
//            if (target.equals("")) {
//                target = "flash";
//            }
//            target += ".zip";
//
//            ZipOutputStream out = new ZipOutputStream(new FileOutputStream(target));
//
//            // Compress the files
//            for (int i = 0; i < sources.size(); i++) {
//                FileInputStream in = new FileInputStream(sources.get(i));
//
//                // Add ZIP entry to output stream.
//                out.putNextEntry(new ZipEntry(sources.get(i)));
//
//                // Transfer bytes from the file to the ZIP file
//                int len;
//                while ((len = in.read(buf)) > 0) {
//                    out.write(buf, 0, len);
//                }
//
//                // Complete the entry
//                out.closeEntry();
//                in.close();
//            }
//
//            // Complete the ZIP file
//            out.close();
//
//            JOptionPane.showMessageDialog(null, "Please, for the love of your phone, make a Nandroid backup. \nThis is an alpha.", "Success!", 1);
//        } catch (FileNotFoundException fnf) {
//            JOptionPane.showMessageDialog(null, "Improper name.", "Error!", 0);
//        } catch (IOException e) {
//            e.printStackTrace();
//        } finally {
//        }
    }//GEN-LAST:event_generateZipButtonActionPerformed

    public static void copyFile(File sourceFile, File destFile) throws IOException {
        if (!destFile.exists()) {
            destFile.createNewFile();
        }

        FileChannel source = null;
        FileChannel destination = null;
        try {
            source = new FileInputStream(sourceFile).getChannel();
            destination = new FileOutputStream(destFile).getChannel();
            destination.transferFrom(source, 0, source.size());
        } finally {
            if (source != null) {
                source.close();
            }
            if (destination != null) {
                destination.close();
            }
        }
    }

    private static void addApp(String sourceLoc, String targetLoc) {
        addApp(null, sourceLoc, targetLoc);
    }

    private static void addApp(String url, String sourceLoc, String targetLoc) {
//        try {
        DownloadFile f = new DownloadFile(url, sourceLoc, targetLoc);
        files.add(f);
        if (url != null) {
            Download.getInstance().addToQueue(url, sourceLoc, targetLoc);
        }
//            File source = new File(sourceLoc);
//            File target = new File(targetLoc);

        //copyFile(source, target);

//        } catch (IOException ex) {
//            Logger.getLogger(Apps.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    private static void removeApp(String s) {
        try {
            File f = new File(s);
            f.delete();
            if (sources.contains(s)) {
                //sources.remove(s);
            }
        } catch (Exception e) {
            System.out.println("error in removeApp");
        }
    }

    public void setZipProgress(int n) {
        zipProgress.setValue(n);
        System.out.println("set to " + n);
        zipProgress.repaint();
    }

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        cleanUp();
        createDirectories();
    }//GEN-LAST:event_formComponentShown

    private void wipeDalvikCacheToggleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wipeDalvikCacheToggleActionPerformed
        if (((JCheckBox) evt.getSource()).isSelected()) {
            wipeDalvik = true;
        } else {
            wipeDalvik = false;
        }
    }//GEN-LAST:event_wipeDalvikCacheToggleActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cleanUp();
    }//GEN-LAST:event_formWindowClosing

    private void mmsDontModifyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmsDontModifyButtonActionPerformed
        try {
            new File("system/app/Mms.apk").delete();
        } catch (Exception e) {
        }
}//GEN-LAST:event_mmsDontModifyButtonActionPerformed

    private void touchWizMmsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_touchWizMmsButtonActionPerformed
        String source = "kitchen/system/app/Mms-TW.apk";
        String target = "system/app/Mms.apk";
        if (this.touchWizMmsButton.isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_touchWizMmsButtonActionPerformed

    private void mmsAospButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mmsAospButtonActionPerformed
        String source = "kitchen/system/app/Mms-AOSP.apk";
        String target = "system/app/Mms.apk";
        if (this.mmsAospButton.isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_mmsAospButtonActionPerformed

    private void miscCarHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miscCarHomeActionPerformed
        String target = "data/app/CarHomeGoogle.apk";
        String source = "kitchen/" + target;
        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
            addApp("kitchen/data/app/CarHomeLauncher.apk", "data/app/CarHomeLauncher.apk");
        } else {
            removeApp(target);
            removeApp("data/app/CarHomeLauncher.apk");
        }
}//GEN-LAST:event_miscCarHomeActionPerformed

    private void miscDockHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miscDockHomeActionPerformed
        String target = "data/app/CradleMain.apk";
        String source = "kitchen/" + target;
        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_miscDockHomeActionPerformed

    private void miscGingerbreadkbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miscGingerbreadkbActionPerformed
        String target = "system/app/ime-mtm-stock-gingerbread.apk";
        String source = "kitchen/" + target;
        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
            addApp("kitchen/system/lib/libjni_latinime.so", "system/lib/libjni_latinime.so");
        } else {
            removeApp(target);
            removeApp("system/lib/libjni_latinime.so");
        }
}//GEN-LAST:event_miscGingerbreadkbActionPerformed

    private void launchersZeamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchersZeamActionPerformed
        String target = "data/app/org.zeam.apk";
        String source = "kitchen/" + target;

        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_launchersZeamActionPerformed

    private void launcherTouchWizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launcherTouchWizActionPerformed
        String target = "system/app/TouchWiz30Launcher.apk";
        String source = "kitchen/" + target;

        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
            addApp("kitchen/system/app/SamsungWidget_CalendarClock.apk", "system/app/SamsungWidget_CalendarClock.apk");
            addApp("kitchen/system/app/SamsungWidget_FeedAndUpdate.apk", "system/app/SamsungWidget_FeedAndUpdate.apk");
            addApp("kitchen/system/app/SamsungWidget_ProgramMonitor.apk", "system/app/SamsungWidget_ProgramMonitor.apk");
            addApp("kitchen/system/app/SamsungWidget_StockClock.apk", "system/app/SamsungWidget_StockClock.apk");
        } else {
            removeApp(target);
            removeApp("system/app/SamsungWidget_CalendarClock.apk");
            removeApp("system/app/SamsungWidget_FeedAndUpdate.apk");
            removeApp("system/app/SamsungWidget_ProgramMonitor.apk");
            removeApp("system/app/SamsungWidget_StockClock.apk");
        }
}//GEN-LAST:event_launcherTouchWizActionPerformed

    private void launchersGingerbreadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchersGingerbreadActionPerformed
        String target = "data/app/Launcher2.apk";
        String source = "kitchen/" + target;

        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_launchersGingerbreadActionPerformed

    private void launchersAdwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchersAdwActionPerformed
        String target = "data/app/org.adw.launcher.apk";
        String source = "kitchen/" + target;

        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_launchersAdwActionPerformed

    private void launchersLauncherProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchersLauncherProActionPerformed
        String target = "data/app/LauncherPro-0.8.2.apk";
        String source = "kitchen/" + target;

        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_launchersLauncherProActionPerformed

    private void VibrantVisualVoicemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VibrantVisualVoicemailActionPerformed
}//GEN-LAST:event_VibrantVisualVoicemailActionPerformed

    private void vibrantWifiCallingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vibrantWifiCallingActionPerformed
        String target = "system/app/WiFi-Calling.apk";
        String source = "kitchen/" + target;

        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
            addApp("kitchen/system/lib/libganril.so", "system/lib/libganril.so");
            addApp("kitchen/system/lib/libkineto.so", "system/lib/libkineto.so");
            addApp("kitchen/system/lib/librilswitch.so", "system/lib/librilswitch.so");
        } else {
            removeApp(target);
            removeApp("system/lib/libganril.so");
            removeApp("system/lib/libkineto.so");
            removeApp("system/lib/librilswitch.so");
        }
}//GEN-LAST:event_vibrantWifiCallingActionPerformed

    private void vibrantMemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vibrantMemoActionPerformed
        String target = "system/app/Memo.apk";
        String source = "kitchen/" + target;
        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_vibrantMemoActionPerformed

    private void vibrantAmazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vibrantAmazonActionPerformed
        String target = "system/app/AmazonMp3.apk";
        String source = "kitchen/" + target;

        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_vibrantAmazonActionPerformed

    private void vibrantKindleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vibrantKindleActionPerformed
        String target = "system/app/KindleStub.apk";
        String source = "kitchen/" + target;
        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_vibrantKindleActionPerformed

    private void vibrantMiniDiaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vibrantMiniDiaryActionPerformed
        String target = "system/app/MiniDiary.apk";
        String source = "kitchen/" + target;
        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_vibrantMiniDiaryActionPerformed

    private void vibrantLayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vibrantLayarActionPerformed
        String target = "system/app/Layar-samsung.apk";
        String source = "kitchen/" + target;
        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_vibrantLayarActionPerformed

    private void vibrantGogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vibrantGogoActionPerformed
        String target = "system/app/GoGo.apk";
        String source = "kitchen/" + target;

        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_vibrantGogoActionPerformed

    private void vibrantWriteandGoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vibrantWriteandGoActionPerformed
        String target = "system/app/WriteandGo.apk";
        String source = "kitchen/" + target;
        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_vibrantWriteandGoActionPerformed

    private void vibrantMediahubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vibrantMediahubActionPerformed
        String target = "system/app/MediaHub.apk";
        String source = "kitchen/" + target;
        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_vibrantMediahubActionPerformed

    private void vibrantAvatarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vibrantAvatarActionPerformed
        String target = "system/app/Avatar.apk";
        String source = "kitchen/" + target;
        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_vibrantAvatarActionPerformed

    private void vibrantAllShareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vibrantAllShareActionPerformed
        String target = "system/app/Dlna.apk";
        String source = "kitchen/" + target;
        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_vibrantAllShareActionPerformed

    private void utilitiesSgsToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilitiesSgsToolsActionPerformed
        String target = "data/app/de.Fr4gg0r.SGS.Tools.apk";
        String source = "kitchen/" + target;

        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_utilitiesSgsToolsActionPerformed

    private void utilitiesSparePartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilitiesSparePartsActionPerformed
        String target = "data/app/com.androidapps.spareparts.apk";
        String source = "kitchen/" + target;
        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_utilitiesSparePartsActionPerformed

    private void utilitiesRomManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilitiesRomManagerButtonActionPerformed
        String target = "data/app/RomManager.apk";
        String source = "kitchen/" + target;

        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_utilitiesRomManagerButtonActionPerformed

    private void utilitiesQuickBootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilitiesQuickBootButtonActionPerformed
        String target = "data/app/Quickboot.apk";
        String source = "kitchen/" + target;

        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_utilitiesQuickBootButtonActionPerformed

    private void utilitiesTitaniumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utilitiesTitaniumButtonActionPerformed
        String target = "data/app/TitaniumBackup.apk";
        String source = "kitchen/" + target;

        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
}//GEN-LAST:event_utilitiesTitaniumButtonActionPerformed

    private void vibrantSlackerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vibrantSlackerActionPerformed
        String target = "system/app/slackerradio.apk";
        String source = "kitchen/" + target;

        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
    }//GEN-LAST:event_vibrantSlackerActionPerformed

    private void vibrantTelenavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vibrantTelenavActionPerformed
        String target = "system/app/Telenav.apk";
        String source = "kitchen/" + target;

        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
    }//GEN-LAST:event_vibrantTelenavActionPerformed

    private void vibrantThinkFreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vibrantThinkFreeActionPerformed
        String target = "system/app/thinkdroid.apk";
        String source = "kitchen/" + target;

        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
    }//GEN-LAST:event_vibrantThinkFreeActionPerformed

    private void vibrantTmoTVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vibrantTmoTVActionPerformed
        String target = "system/app/com.mobitv.client.mobitv.apk";
        String source = "kitchen/" + target;

        if (((JCheckBox) evt.getSource()).isSelected()) {
            addApp(source, target);
        } else {
            removeApp(target);
        }
    }//GEN-LAST:event_vibrantTmoTVActionPerformed

    private void systemMmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemMmsActionPerformed
        if (((JComboBox) evt.getSource()).getSelectedItem().equals("AOSP Mms")) {
            String url = "http://www.rbirg.com/vibrant/kitchen/system/app/Mms-TW.apk";
            String source = "kitchen/system/app/Mms-TW.apk";
            String target = "system/app/Mms.apk";
            addApp(url, source, target);
        } else if (((JComboBox) evt.getSource()).getSelectedItem().equals("TouchWiz Mms")) {
            
        }
    }//GEN-LAST:event_systemMmsActionPerformed

    private void downloadFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadFilesActionPerformed
        Download.getInstance().execute();
    }//GEN-LAST:event_downloadFilesActionPerformed

    public void setStatus(String s) {
        this.statusText.setText(s);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
            System.out.println("Look and feel failure");
        }
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Apps().setVisible(true);
            }
        });



    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup MmsGroup;
    private javax.swing.ButtonGroup ModemGroup;
    private javax.swing.JCheckBox VibrantVisualVoicemail;
    private javax.swing.JButton downloadFiles;
    public javax.swing.JButton generateZipButton;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JCheckBox launcherTouchWiz;
    private javax.swing.JCheckBox launchersAdw;
    private javax.swing.JCheckBox launchersGingerbread;
    private javax.swing.JCheckBox launchersLauncherPro;
    private javax.swing.JCheckBox launchersZeam;
    private javax.swing.JCheckBox miscCarHome;
    private javax.swing.JCheckBox miscDockHome;
    private javax.swing.JCheckBox miscGingerbreadkb;
    private javax.swing.JRadioButton mmsAospButton;
    private javax.swing.JRadioButton mmsDontModifyButton;
    private javax.swing.JLabel statusText;
    private javax.swing.JComboBox systemMms;
    private javax.swing.JRadioButton touchWizMmsButton;
    private javax.swing.JPanel utilitiesPanel;
    private javax.swing.JCheckBox utilitiesQuickBootButton;
    private javax.swing.JCheckBox utilitiesRomManagerButton;
    private javax.swing.JCheckBox utilitiesSgsTools;
    private javax.swing.JCheckBox utilitiesSpareParts;
    private javax.swing.JCheckBox utilitiesTitaniumButton;
    private javax.swing.JCheckBox vibrantAllShare;
    private javax.swing.JCheckBox vibrantAmazon;
    private javax.swing.JCheckBox vibrantAvatar;
    private javax.swing.JCheckBox vibrantGogo;
    private javax.swing.JCheckBox vibrantKindle;
    private javax.swing.JCheckBox vibrantLayar;
    private javax.swing.JCheckBox vibrantMediahub;
    private javax.swing.JCheckBox vibrantMemo;
    private javax.swing.JCheckBox vibrantMiniDiary;
    private javax.swing.JCheckBox vibrantSlacker;
    private javax.swing.JCheckBox vibrantTelenav;
    private javax.swing.JCheckBox vibrantThinkFree;
    private javax.swing.JCheckBox vibrantTmoTV;
    private javax.swing.JCheckBox vibrantWifiCalling;
    private javax.swing.JCheckBox vibrantWriteandGo;
    private javax.swing.JCheckBox wipeDalvikCacheToggle;
    public javax.swing.JTextField zipName;
    public javax.swing.JProgressBar zipProgress;
    // End of variables declaration//GEN-END:variables
}
